name: Deploy to salesdforce CI CD enivorment on push to  master # when any code push the main or any branch merge 

on:
 push:
  branches: [ master ] # when any code push the main or any branch merge
  paths:
    - 'force-app/**'  # If somthing is chnage in the force-app so this job should be triggerd

jobs:
  Deploy-to-sandbox:
    runs-on: ubuntu-latest  # most frequently use in CI CD
    environment: sandbox  # used when you have enviroment in github here we do not have
    steps:
      - uses: actions/setup-node@v3  # setup node.js
        with:
          node-version: '18'

      - name: 'Checkout source code'
        uses: actions/checkout@v3  # copying / checking out source code 
        with:
          fetch-depth: '2'

      # Now Install Salesforce CLI
      - name: 'Install sfdx'
        run: npm install @salesforce/cli --global

      - name: 'Installing sfdx git delta'
        run: |
          echo Y | sfdx plugins:install sfdx-git-delta  
          sfdx plugins
                         
      - name: 'Create delta packages'
        run: |
          mkdir changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/
          echo "[INFO] Diff generated"

      - name:  'Deploy to environment with running all local tests'  # JWT_SERVER_KEY from the secret of github asseccing all the key and variable
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt --username ${{ secrets.DEPLOYMENT_USER_NAME }} --jwt-key-file server.key \
            --client-id ${{ secrets.CONSUMER_KEY }} --instance-url ${{ vars.INSTANCE_URL }} \
            --set-default
          sf project deploy start --source-dir changed-sources/force-app --test-level RunLocalTests

          

