name: Deploy to Dev and UAT

on:
  push:
    branches: [ uat ]
    paths:
      - 'force-app/**'

jobs:

  deploy-to-uat:
                                  # needs: deploy-to-dev     # Only run UAT if Dev was successful
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Install sfdx-git-delta
        run: |
          echo Y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: Create delta for UAT
        run: |
          mkdir changed-sources
          sf sgd source delta --to "HEAD" --from "HEAD~1" \
            --output changed-sources/ --generate-delta --source force-app/

      - name: Deploy to UAT Org
        run: |
          echo "${{ secrets.UAT_SERVER_KEY }}" > server.key
          sf org login jwt --username ${{ secrets.UAT_DEPLOYMENT_USERNAME }} \
            --jwt-key-file server.key --client-id ${{ secrets.UAT_CONSUMER_KEY }} \
            --instance-url ${{ vars.UAT_INSTANCE_URL }} --set-default

          sf project deploy start --source-dir changed-sources/force-app \
            --test-level RunLocalTests
